require:
  - rubocop-sequel
  - rubocop-rspec
inherit_from: .rubocop_todo.yml

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/BlockDelimiters:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false
